---
- hosts: all
  become: true
  tasks:
  - name: Instala nginx
    yum:
      name: nginx
      state: installed

  - name: nginx is running and enabled
    service:
      name: nginx
      state: started
      enabled: yes
      when: ansible_os_family == "CentOS"
